# --- Estágio 1: Definir a imagem base ---
FROM nginx:alpine

# --- Estágio 2: Copiar os arquivos do projeto ---
COPY ./index.html /usr/share/nginx/html/index.html

# --- Estágio 3: Expor a porta ---
EXPOSE 80
